version: 2

sources:
  - name: conformed
    database: raw
    schema: conformed

    tables:
      - name: DateDimension
        columns:
          - name: DateKey
            tests:
              - unique


  - name: northwind
    database: raw
    schema: northwind

    tables:
      - name: Customers
        columns:
          - name: CustomerId
            tests:
              - unique
      - name: Products
        columns:
          - name: ProductId
            tests:
              - unique        
      - name: Suppliers
        columns:
          - name: SupplierId
            tests:
              - unique        
      - name: Categories
        columns:
          - name: CategoryId
            tests:
              - unique
      - name: Employees
        columns:
          - name: EmployeeId
            tests:
              - unique
      - name: Shippers
        columns:
          - name: ShipperID
            tests:
              - unique      
      - name: Orders
        columns:
          - name: OrderId
            tests:
              - unique                                                  
      - name: Order_Details
        tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - OrderId
              - ProductId

  - name: fugdeflix_v3
    database: raw
    schema: fudgeflix_v3

    tables:
      - name: ff_accounts
      - name: ff_account_billing

  - name: fugdemart_v3
    database: raw
    schema: fudgemart_v3

    tables:
      - name: fm_customers
      - name: fm_orders
      - name: fm_order_details
      - name: fm_products
